List<Map<String,dynamic>> dummyproducts=[
  {
    "id":100,
    "name":"Laptop",
    "Price":"60,000",
    "image":"assets/images/lap.jpg",
    "details":"hp"
  },
  {
    "id":101,
    "name":"Mobile",
    "Price":"50,000",
    "image":"assets/images/Mob.jpg",
    "details":"Apple"
  },
  {
    "id":102,
    "name":"Watch",
    "Price":"25,000",
    "image":"assets/images/watch.jpg",
    "details":"Apple"
  },
  {
    "id":103,
    "name":"headphone",
    "Price":"3000",
    "image":"assets/images/headphone.jpg",
    "details":"huawei"
  },
];